Repository adenild/otma-vue, pull requests merged in 2019-03, with the labels that each got.

#1 PR#1
  components.js
  index.html
Labels: merge

#2 PR#2
  components.js
  index.html
  index.js
Labels: conflito, corrigido

#3 PR#3
  components/form-components.js
  components/input-components.js
  components/table-components.js
  index.css
  index.html
  index.js
Labels: merge

#5 PR#5
  components/table-components.js
  index.html
  index.js
  node_modules/vue-the-mask/README.md
  node_modules/vue-the-mask/dist/vue-the-mask.js
  node_modules/vue-the-mask/package.json
  node_modules/vue-the-mask/src/component.vue
  node_modules/vue-the-mask/src/directive.js
  node_modules/vue-the-mask/src/dynamic-mask.js
  node_modules/vue-the-mask/src/index.js
  node_modules/vue-the-mask/src/masker.js
  node_modules/vue-the-mask/src/maskit.js
  node_modules/vue-the-mask/src/tokens.js
  package-lock.json
Labels: merge

#6 PR#6
  components/table-components.js
Labels: conflito

#7 PR07
  index.html
Labels: merge

#8 PR08
  index.html
Labels: merge

#11 PR#11
  index.html
Labels: merge

#13 PR final
  components/form-components.js
  components/input-components.js
  components/table-components.js
  index.html
  index.js
  joao/components/closed.js
  joao/components/open.js
  joao/joao.html
  joao/joao.js
Labels: conflito, corrigido
